//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZaposliMe.Frontend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZaposliMe.Frontend.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept application to see phone.
        /// </summary>
        public static string AcceptApplicationToSeePhone {
            get {
                return ResourceManager.GetString("AcceptApplicationToSeePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job.
        /// </summary>
        public static string AddJob {
            get {
                return ResourceManager.GetString("AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree that my data will be used to contact me regarding this request..
        /// </summary>
        public static string AgreeThatMyDataWillBeUsed {
            get {
                return ResourceManager.GetString("AgreeThatMyDataWillBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lready applied to this job..
        /// </summary>
        public static string AlreadyAppliedToThisJob {
            get {
                return ResourceManager.GetString("AlreadyAppliedToThisJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string AlreadyHavaAnAccount {
            get {
                return ResourceManager.GetString("AlreadyHavaAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Details.
        /// </summary>
        public static string ApplicationDetails {
            get {
                return ResourceManager.GetString("ApplicationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications to my jobs.
        /// </summary>
        public static string ApplicationsToMyJobs {
            get {
                return ResourceManager.GetString("ApplicationsToMyJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied.
        /// </summary>
        public static string Applied {
            get {
                return ResourceManager.GetString("Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for.
        /// </summary>
        public static string ApplyFor {
            get {
                return ResourceManager.GetString("ApplyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying is not possible at the moment. Please try again later..
        /// </summary>
        public static string ApplyingIsNotPossibleAtTheMoment {
            get {
                return ResourceManager.GetString("ApplyingIsNotPossibleAtTheMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply with one click.
        /// </summary>
        public static string ApplyWithOneClick {
            get {
                return ResourceManager.GetString("ApplyWithOneClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve or Reject Application.
        /// </summary>
        public static string ApproveOrRejectApplication {
            get {
                return ResourceManager.GetString("ApproveOrRejectApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve / Reject.
        /// </summary>
        public static string ApproveReject {
            get {
                return ResourceManager.GetString("ApproveReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete .
        /// </summary>
        public static string AreYouSureYouWantToDelete {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to withdraw your application for.
        /// </summary>
        public static string AreYouSureYouWantWithdrawApplication {
            get {
                return ResourceManager.GetString("AreYouSureYouWantWithdrawApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Jobs.
        /// </summary>
        public static string AvailableJobs {
            get {
                return ResourceManager.GetString("AvailableJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rating.
        /// </summary>
        public static string AverageRating {
            get {
                return ResourceManager.GetString("AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become an employer.
        /// </summary>
        public static string BecomeEmployer {
            get {
                return ResourceManager.GetString("BecomeEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a worker.
        /// </summary>
        public static string BecomeWorker {
            get {
                return ResourceManager.GetString("BecomeWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse jobs.
        /// </summary>
        public static string BrowseJobs {
            get {
                return ResourceManager.GetString("BrowseJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse openings and save favorites.
        /// </summary>
        public static string BrowseOpeningsAndSaveFavorites {
            get {
                return ResourceManager.GetString("BrowseOpeningsAndSaveFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By continuing, you agree to our.
        /// </summary>
        public static string ByContinuingYouAgreeToOur {
            get {
                return ResourceManager.GetString("ByContinuingYouAgreeToOur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click a star to rate (1–5)..
        /// </summary>
        public static string ClickStarToRate {
            get {
                return ResourceManager.GetString("ClickStarToRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Count.
        /// </summary>
        public static string CommentCount {
            get {
                return ResourceManager.GetString("CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (optional).
        /// </summary>
        public static string CommentOptional {
            get {
                return ResourceManager.GetString("CommentOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm withdraw.
        /// </summary>
        public static string ConfirmWithdraw {
            get {
                return ResourceManager.GetString("ConfirmWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact details.
        /// </summary>
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account quickly and get instant access to jobs or candidates..
        /// </summary>
        public static string CreateAnAcountQuickly {
            get {
                return ResourceManager.GetString("CreateAnAcountQuickly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a job post.
        /// </summary>
        public static string CreateJobPost {
            get {
                return ResourceManager.GetString("CreateJobPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a profile.
        /// </summary>
        public static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        public static string CreateYourAccount {
            get {
                return ResourceManager.GetString("CreateYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first posting now.
        /// </summary>
        public static string CreateYourFirstPostingNow {
            get {
                return ResourceManager.GetString("CreateYourFirstPostingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct connection worker ↔ employer, per hour or per day..
        /// </summary>
        public static string DirectConnectionWorkerEmployerPerHourOrPerDay {
            get {
                return ResourceManager.GetString("DirectConnectionWorkerEmployerPerHourOrPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an account?.
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to approve or reject .
        /// </summary>
        public static string DoYou_WantToApproveOrReject {
            get {
                return ResourceManager.GetString("DoYou WantToApproveOrReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to apply to this job?.
        /// </summary>
        public static string DoYouWantToApplyToThisJob {
            get {
                return ResourceManager.GetString("DoYouWantToApplyToThisJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email already exists..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email already exists..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is used as your account identifier..
        /// </summary>
        public static string EmailIsUsedAsYouraccountIdentifier {
            get {
                return ResourceManager.GetString("EmailIsUsedAsYouraccountIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string Employer {
            get {
                return ResourceManager.GetString("Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Reviews.
        /// </summary>
        public static string EmployerReviews {
            get {
                return ResourceManager.GetString("EmployerReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employers: skip negotiations, skip the “someone knows someone” phase — connect straight with people who are ready to work and get things done..
        /// </summary>
        public static string EmployersSkipNegotiationsSkipSomeoneKnowsSomeonePhaseConnectStraight {
            get {
                return ResourceManager.GetString("EmployersSkipNegotiationsSkipSomeoneKnowsSomeonePhaseConnectStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expect a call from the employer.
        /// </summary>
        public static string ExpectCallFromEmployer {
            get {
                return ResourceManager.GetString("ExpectCallFromEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast &amp; simple.
        /// </summary>
        public static string FastAndSimple {
            get {
                return ResourceManager.GetString("FastAndSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in your details to get started.
        /// </summary>
        public static string FillInYourDetailsToGetStarted {
            get {
                return ResourceManager.GetString("FillInYourDetailsToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out the form.
        /// </summary>
        public static string FillOutTheForm {
            get {
                return ResourceManager.GetString("FillOutTheForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find job nearby or post a job in your area..
        /// </summary>
        public static string FindJobNearbyOrPostJobInYourArea {
            get {
                return ResourceManager.GetString("FindJobNearbyOrPostJobInYourArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find work. Hire worker..
        /// </summary>
        public static string FindWorkHireWorker {
            get {
                return ResourceManager.GetString("FindWorkHireWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focused on nearby opportunities so hiring and onboarding are fast and personal..
        /// </summary>
        public static string FocusedOnNearbyOpportunities {
            get {
                return ResourceManager.GetString("FocusedOnNearbyOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Employers.
        /// </summary>
        public static string ForEmployers {
            get {
                return ResourceManager.GetString("ForEmployers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For employers — how it works.
        /// </summary>
        public static string ForEmployersHowItWorks {
            get {
                return ResourceManager.GetString("ForEmployersHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget middlemen, agencies and hidden fees — get a job or find workers directly on.
        /// </summary>
        public static string ForgetMiddlemenAgenciesAndHiddenFees {
            get {
                return ResourceManager.GetString("ForgetMiddlemenAgenciesAndHiddenFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Workers.
        /// </summary>
        public static string ForWorkers {
            get {
                return ResourceManager.GetString("ForWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For workers — how it works.
        /// </summary>
        public static string ForWorkersHowItWorks {
            get {
                return ResourceManager.GetString("ForWorkersHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free for all.
        /// </summary>
        public static string FreeForAll {
            get {
                return ResourceManager.GetString("FreeForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started takes a minute..
        /// </summary>
        public static string GettingStartedTakesAMinute {
            get {
                return ResourceManager.GetString("GettingStartedTakesAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string IvalidLogin {
            get {
                return ResourceManager.GetString("IvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Created.
        /// </summary>
        public static string JobCreated {
            get {
                return ResourceManager.GetString("JobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave or see reviews.
        /// </summary>
        public static string LeaveOrSeeReviews {
            get {
                return ResourceManager.GetString("LeaveOrSeeReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review.
        /// </summary>
        public static string LeaveReview {
            get {
                return ResourceManager.GetString("LeaveReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local-first.
        /// </summary>
        public static string LocalFirst {
            get {
                return ResourceManager.GetString("LocalFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as .
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made for everyone.
        /// </summary>
        public static string MadeForEveryone {
            get {
                return ResourceManager.GetString("MadeForEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Applications.
        /// </summary>
        public static string MyApplications {
            get {
                return ResourceManager.GetString("MyApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help for the weekend, the season, or “right now”? Skip intermediaries and hidden costs — post a job, receive applications and contact people directly. Šljakomat shortens the path from need → completed task..
        /// </summary>
        public static string NeedHelpForThe_weekendTheSeasonOrRigntNow {
            get {
                return ResourceManager.GetString("NeedHelpForThe weekendTheSeasonOrRigntNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comment provided..
        /// </summary>
        public static string NoComment {
            get {
                return ResourceManager.GetString("NoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available..
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs available..
        /// </summary>
        public static string NoJobsAvailable {
            get {
                return ResourceManager.GetString("NoJobsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No middlemen. No fees..
        /// </summary>
        public static string NoMiddlemenNoFees {
            get {
                return ResourceManager.GetString("NoMiddlemenNoFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more begging, calling, asking “is there a daily job available?”. Create a profile and apply without waiting for permission. Your work speaks for you..
        /// </summary>
        public static string NoMoreBeggingCallingAsking {
            get {
                return ResourceManager.GetString("NoMoreBeggingCallingAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reviews found..
        /// </summary>
        public static string NoReviewsFound {
            get {
                return ResourceManager.GetString("NoReviewsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user data was returned..
        /// </summary>
        public static string NoUserDataWasReturned {
            get {
                return ResourceManager.GetString("NoUserDataWasReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Workers.
        /// </summary>
        public static string NumberOfWorkers {
            get {
                return ResourceManager.GetString("NumberOfWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you accept an application, you&apos;ll see the worker’s contact details.
        /// </summary>
        public static string OnceYouAcceptAapplicationYouWllSeeTheWokersCntactDetails {
            get {
                return ResourceManager.GetString("OnceYouAcceptAapplicationYouWllSeeTheWokersCntactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (optional).
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string OptionalOption {
            get {
                return ResourceManager.GetString("OptionalOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit (0–9)..
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one non-alphanumeric character..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required..
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select city.
        /// </summary>
        public static string PleaseSelectCity {
            get {
                return ResourceManager.GetString("PleaseSelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a job in minutes.
        /// </summary>
        public static string PostAJobInMinutes {
            get {
                return ResourceManager.GetString("PostAJobInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted from.
        /// </summary>
        public static string PostedFrom {
            get {
                return ResourceManager.GetString("PostedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted to.
        /// </summary>
        public static string PostedTo {
            get {
                return ResourceManager.GetString("PostedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish roles with clear requirements.
        /// </summary>
        public static string PublishRolesWithClearRequirements {
            get {
                return ResourceManager.GetString("PublishRolesWithClearRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions or feedback? Send us a message..
        /// </summary>
        public static string QuestionsFeedback {
            get {
                return ResourceManager.GetString("QuestionsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready? No fees, no waiting — just an agreement..
        /// </summary>
        public static string ReadyNoFeesNoWiting {
            get {
                return ResourceManager.GetString("ReadyNoFeesNoWiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive and review applications.
        /// </summary>
        public static string ReceiveAndReviewApplications {
            get {
                return ResourceManager.GetString("ReceiveAndReviewApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as Employer.
        /// </summary>
        public static string RegisterAsEmployer {
            get {
                return ResourceManager.GetString("RegisterAsEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as Worker.
        /// </summary>
        public static string RegisterAsWorker {
            get {
                return ResourceManager.GetString("RegisterAsWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as Employer.
        /// </summary>
        public static string RegisterАsEmployer {
            get {
                return ResourceManager.GetString("RegisterАsEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review submitted..
        /// </summary>
        public static string ReviewSubmitted {
            get {
                return ResourceManager.GetString("ReviewSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total reviews.
        /// </summary>
        public static string RotalReviewsLower {
            get {
                return ResourceManager.GetString("RotalReviewsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to continue.
        /// </summary>
        public static string SignInToContinue {
            get {
                return ResourceManager.GetString("SignInToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up in a minute, apply with one click, get contacted directly..
        /// </summary>
        public static string SignUpInMinuteApplyWithOneClickGetContactedDirectly {
            get {
                return ResourceManager.GetString("SignUpInMinuteApplyWithOneClickGetContactedDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start applying today.
        /// </summary>
        public static string StartApplyingToday {
            get {
                return ResourceManager.GetString("StartApplyingToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit review.
        /// </summary>
        public static string SubmitReview {
            get {
                return ResourceManager.GetString("SubmitReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This employer has no individual reviews yet..
        /// </summary>
        public static string ThisEmployerHasNoIndividualReviewsYet {
            get {
                return ResourceManager.GetString("ThisEmployerHasNoIndividualReviewsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job is already full. You cannot apply..
        /// </summary>
        public static string ThisJobIsAlreadyFull {
            get {
                return ResourceManager.GetString("ThisJobIsAlreadyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tired of scrolling through Viber groups and asking around just to find a daily job?.
        /// </summary>
        public static string TiredOfScrollingThroughViberGroupsAndAskingAroundJustToFindDailyJob {
            get {
                return ResourceManager.GetString("TiredOfScrollingThroughViberGroupsAndAskingAroundJustToFindDailyJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Reviews.
        /// </summary>
        public static string TotalReviews {
            get {
                return ResourceManager.GetString("TotalReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track applications and manage them.
        /// </summary>
        public static string TrackApplicationsAndManageThem {
            get {
                return ResourceManager.GetString("TrackApplicationsAndManageThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track application status.
        /// </summary>
        public static string TrackApplicationStatus {
            get {
                return ResourceManager.GetString("TrackApplicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your pipeline in one place.
        /// </summary>
        public static string TrackYourPipelineInOnePlace {
            get {
                return ResourceManager.GetString("TrackYourPipelineInOnePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        public static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        public static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers track applications; employers publish roles and review applicants in one place..
        /// </summary>
        public static string WorkersAndEmployerInOnePlace {
            get {
                return ResourceManager.GetString("WorkersAndEmployerInOnePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers browse and apply to jobs; employers post roles and manage applicants..
        /// </summary>
        public static string WorkersBrowseEmployersPostRoles {
            get {
                return ResourceManager.GetString("WorkersBrowseEmployersPostRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers needed.
        /// </summary>
        public static string WorkersNeeded {
            get {
                return ResourceManager.GetString("WorkersNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, apply.
        /// </summary>
        public static string YesApply {
            get {
                return ResourceManager.GetString("YesApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already logged in as.
        /// </summary>
        public static string YouAreAlreadyLoggedInAs {
            get {
                return ResourceManager.GetString("YouAreAlreadyLoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no applications yet..
        /// </summary>
        public static string YouHaveNoApplicationsYet {
            get {
                return ResourceManager.GetString("YouHaveNoApplicationsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be signed in to view your profile..
        /// </summary>
        public static string YouNeedToBeSignedInToViewProfile {
            get {
                return ResourceManager.GetString("YouNeedToBeSignedInToViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application could not be submitted..
        /// </summary>
        public static string YourApplicationCouldNotBeSubmitted {
            get {
                return ResourceManager.GetString("YourApplicationCouldNotBeSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent. We’ll get back to you soon..
        /// </summary>
        public static string YourMessageHasBeenSent {
            get {
                return ResourceManager.GetString("YourMessageHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message is transmitted securely over HTTPS..
        /// </summary>
        public static string YourMessageIsTransmittedSecurelyOver_HTTPS {
            get {
                return ResourceManager.GetString("YourMessageIsTransmittedSecurelyOver HTTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully applied for job.
        /// </summary>
        public static string YouSuccessfullyAppliedForJob {
            get {
                return ResourceManager.GetString("YouSuccessfullyAppliedForJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully registered. Now you can.
        /// </summary>
        public static string YouSuccessfullyRegisteredNowYouCan {
            get {
                return ResourceManager.GetString("YouSuccessfullyRegisteredNowYouCan", resourceCulture);
            }
        }
    }
}
